### ISSUE TITLE
AMQPOutput does not set delivery-mode correctly

### ISSUE THREAD

**Issue by ioc32** [mozilla-services/heka#1235]
It appears heka-0.8 is not setting the appropriate delivery-mode when the 'persistent' option [1] is used in the AMQPOutput plugin.

Please see the AMQPOutput TOML section [2]. Messages routed to this output look like so [3], according to a sample message dequeued right in the RabbitMQ management plugin UI.

Looking at the code [4], the plugin sets this config parameter to '1' if persistence is requested, '0' otherwise. To this regard, the AMQP 0.9.1 reference [5] states:

"octet delivery-mode: Non-persistent (1) or persistent (2)"

Is this something that needs changing, or am I missing something (heka, RabbitMQ-wise)?

Thanks in advance, guys, heka is shaping up great!

[1] http://hekad.readthedocs.org/en/v0.8.0/config/outputs/index.html#amqpoutput
[2] https://gist.github.com/ioc32/4a519ed9f89f6d5563bd
[3] https://gist.github.com/ioc32/ba300d119b7d88ebee51
[4] https://github.com/mozilla-services/heka/blob/dev/plugins/amqp/amqp_output.go#L144-L147
[5] https://www.rabbitmq.com/amqp-0-9-1-reference.html

**Comment by ioc32** [comment]
FWIW I've built heka with these changes and they work fine. Please see this gist [1] with the heka config and two sample messages from the queue.

The resulting binary passed all the tests.

[1] https://gist.github.com/ioc32/9e64a9948333fd9b126f

**Comment by vino-tha** [comment]
Hi ioc32,

Currently i am using heka-0.8.3 with Rabbitmq-3.5.6-1, Even after setting the persistent=true in Heka, Rabbitmq does not persist the messages, When i tried with python code to send persistent messages, rabbitmq is able to persist them.
Could you please confirm if this issue is fixed in Heka-0.8.3

Thanks,
Vino

**Comment by rafrombrc** [comment]
It is not fixed in 0.8.3. It is fixed in 0.9 and later. 0.9 came out almost a year ago, it is highly recommended you upgrade.

If upgrading is not an option for you, you can fix the issue by building from source applying the [necessary change](https://github.com/mozilla-services/heka/commit/af4637f15192a14909df61243af1df541d60b2a9) to the v0.8.3 tag. We have no plans of making any further 0.8.x releases.
