### ISSUE TITLE
Elasticsearch messages

### ISSUE THREAD

**Issue by carlosvega** [mozilla-services/heka#1287]
Hi, I'm trying to send messages from logstash to elasticsearch through Heka with RabbitMQ as AMQP
With ESJsonEncoder or ESLogstashV0Encoder the messages in elasticsearch appear with a field called "messages" that includes the Payload, the JSON message. I would like to have that JSON as fields with the rest of the message.

I did a lua script for the sandbox encoder but I receive 500 server error from elasticsearch when using ElasticSearchOutput. I would like to know a way to do this or the format I need to avoid 500 server errors when modifying the messages.

Also, the index field gets the a random timestamp like year 1750-5-23 not sure why. I would like to get the date from the timestamp in the Payload.

Convert: 
{index: …
type: …
uuid: …
message: "{field1: …, field2: … etc}"
}

to 

{index: …
type: …
uuid: …
field1: …
field2: …
field3: …
}

**Comment by rafrombrc** [comment]
This issue tracker is intended for bug reports or feature requests, it's not a good venue for getting support. To ask questions you'll get a much better response either in the #heka channel on irc.mozilla.org (esp during California working hours) or on the [mailing list](https://mail.mozilla.org/listinfo/heka). I recommend you re-ask this question on the mailing list.

The short answer, though, is that to use those encoders you'd want your data to already be parsed from the payload and stored in message fields. Usually this happens in a decoder on the way in. You *could* do this in a SandboxEncoder, though. I wouldn't be able to help you w/ the 500 error w/o considerably more information.

Also, I'm not sure if you really are intending to send data from logstash to elasticsearch going through AMQP and heka along the way, but if so that seems... excessive. Usually you'd use either logstash *or* heka, I can't think of a reason why you'd want to use both.

Anyway, please ask further support questions in a different venue. Thanks! :)
