### ISSUE TITLE
Add reporting for splitters

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1313]
Splitter plugins aren't currently showing up in the dashboard or SIGUSR1 reports. Related: #1312.

**Comment by 4r9h** [comment]
Hi, I've read through the code as you asked on IRC.
My initial thoughts are (sorry for some oversimplifications):
* Decoders are displayed in reports because their runners are available in "global" slice called allDecoders.
* DecoderRunners register themselves in this slice and because of that reporting module can generate reports for all decoders.
* Runners implement mostly asynchronous communication via channels.
* However, deliverer reimplements part of runner functionality to provide "synchronous" feature for running decoders. That's 2 different places for "the same" thing. I think deliverer makes it a little more hidden.
* One of the first thoughts ws to provide new base interface (called e.g. DecoderBaseRunner) for runners and move current DecoderRunner into DecoderRunnerAsync and create second implementation called DecoderRunnerSync. However, i think it is overengineering.
* Second idea was to remove current code related to syncdecode from deliverer and add simple waitgroup and later pass it  (together with pack via new struct) to the decoder and just .wait() until runner calls .done(). I think that's the better option to implement because leaves runners almost untouched (and the reporting layers) and don't change interfaces of existing decoders.

@rafrombrc what do you think?
