### ISSUE TITLE
Improve sandbox message API

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/heka#1351]
Parts of the sandbox's message API operate on a semi-hidden message (`read_message()`, `write_message()`), while other parts operate on Lua values (`inject_message()`, `inject_payload()`).  It would be nice to be able to do more operations on that "on deck" message - read it, modify it, inject it, and create a new one.

My use case is a decoder designed to pass along the incoming message "as-is" and create and inject a second message based on the original. Currently I need to create a copy of the incoming message field-by-field, inject that, then construct another message. It would be simpler (and probably more performant) to simply output the "on-deck" message and inject the second one.

Adding multiple instances of a field can't really be done in a Lua table (and using `inject_message`), so that would be another small win.

**Comment by trink** [comment]
You can use read_message("raw") and  the new decode_message (when merged) to pull down the entire message modify it and re-inject it.  That PR https://github.com/mozilla-services/lua_sandbox/pull/72 also support an array of fields.  The only remaining issue is that read_message("raw") in most cases will return a stale message (since Heka does not re-encode a message after mutation https://github.com/mozilla-services/heka/issues/1342) but in your decoder case you should be in good shape since you are reading a protobuf input.

https://github.com/mozilla-services/heka/issues/1344

**Comment by trink** [comment]
The landed PRs above address this issue.
