### ISSUE TITLE
Correct the remaining issues with #1296

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1380]
https://github.com/mozilla-services/heka/pull/1296#issuecomment-72560897

**Comment by rafrombrc** [comment]
The only issue that wasn't addressed in the comments on #1296 is the no-op vs error comment, and I'm not sure I agree that deleting a value that doesn't exist should be a no-op instead of an error. I think it would be very confusing to silently not-fail if someone tries to delete a non-existent array index in a field, for instance. Maybe we need to add the ability to check for field existence?

**Comment by trink** [comment]
The removed unit test was not added back in.

The use case for making delete a no-op on missing data is for our own PII scrubber in which a lot of the fields being removed are optional.  Having to pcall each one just to throw away the error is a pita.  I am just saying the final result of a delete on an existing field is is the same as the result on a non-existent field (the field you don't want to be there isn't).

An option would be acceptable

**Comment by rafrombrc** [comment]
Okay, I re-added the test that was removed. I also changed the behaviour so deleting a non-existent field is a no-op. Trying to delete an out-of-bounds field or array index for a field that does exist is still an error, however, and I added some tests (and fixed some bugs) to show that.

Does that behaviour work for you?
