### ISSUE TITLE
Misunderstanding about Type when inject_message in Filters

### ISSUE THREAD

**Issue by hoffoo** [mozilla-services/heka#1446]
From the docs: "Type is prepended with “heka.sandbox.” by the SandboxFilter to avoid data confusion/mis-representation."

I guess I am confused about why this happens in filters. Should I create a decoder that matches "heka.sandbox*" if I really do want Type not be modified?

**Comment by rafrombrc** [comment]
So you know, the [mailing list](https://mail.mozilla.org/listinfo/heka) is a better venue for asking questions, we try to keep the issue tracker focused on actual bug reports and feature requests.

To answer you, however, it's possible to inject SandboxFilters from a remote machine into a running Heka instance. For this reason, SandboxFilters are assumed to sometimes be running untrusted code, and there are a number of restrictions placed on them to try to prevent nefarious actors from DoS'ing or otherwise interfering with Heka's intended behavior. SandboxDecoders can only run code that actually lives on the file system of the Heka server, so it is assumed to be more trusted code and thus has more complete control over the generated output.

I'm not sure what you mean by "Should I create a decoder that matches... ". More information about your use case would be valuable. But, again, the mailing list is a better venue. Thanks.

**Comment by hoffoo** [comment]
@rafrombrc very cool, makes sense. sorry for spamming here!
