### ISSUE TITLE
Custom Sandbox script types

### ISSUE THREAD

**Issue by tdavis** [mozilla-services/heka#1501]
This kinda extends from #1500. Since there's such push-back against customizing which methods/modules are exposed by the provided Lua Sandbox, are there any plans to flesh out the Sandbox script type system? the ``switch`` on script type seems to indicate a desire to, but the configuration is pretty coupled with the current Lua sandbox. Doing so would prevent your "average joe" from exposing Lua scripts just by editing a config file, but would definitely help those of us stuck patching and/or copying Heka sources.

**Comment by rafrombrc** [comment]
When building Heka we made design choices to allow for the possibility of other sandbox engines, such as Javascript or Python. It's still theoretically possible for someone to implement another sandbox engine, and if someone stepped forward to do so then we would take care to make sure that the Heka core didn't prevent that effort from succeeding.

Integrating another sandbox engine would be a *lot* of work, however, and that's work that the core Heka team has no intention of tackling. Over time more and more of the functionality that makes Heka valuable has been implemented in Lua. So much so that we're event experimenting with using the Sandbox in non-Heka contexts (see https://github.com/trink/hindsight). Even if all of the sandbox's functionality were duplicated in a different scripting language, it would likely not perform as well as the Lua implementations.

What are the use cases you have for which you're interested in extending the current sandbox implementation?

Out of curiosity, what is the

**Comment by tdavis** [comment]
I'm perfectly happy with Lua, I just wish the Sandbox plugin APIs were a little more granular or easy to extend. For instance, ``SandboxFilter.Init()`` (or any ``SandboxFoo.Init()``; they overlap considerably) contains the logic for how to get something satisfying ``Sandbox``, mixed in with other initialization logic. This requires that I copy all of ``sandbox_filter.go`` into my project and register something like ``SandboxFilter2`` instead of registering a simple factory that would produce structs satisfying ``Sandbox`` for my own script type (call it "lua2"). See also: ``SandboxManagerFilter`` which requires the same level of duplication because it expects the filter type to be "SandboxFilter" or it just gives up. (Sadly, plugin_loader imports heka's packages after mine, so I can't just register over SandboxFilter)

I think the high reliance on Lua for the runtime exacerbates the issue for me. I want to implement as much of my filtering and so forth in Lua as possible, but the lack of any ability to customize which methods and functions are "banned" makes it difficult. If the interfaces were a bit more formalized and decoupled from the guts, doing what I need to do to keep using Lua would be much more convenient.

**Comment by trink** [comment]
The sandbox restrictions are carefully chosen for the stability of Heka and will remain predefined.
