### ISSUE TITLE
GELF encoder

### ISSUE THREAD

**Issue by haf** [mozilla-services/heka#1584]
Greetings,

Say I wanted to send data to Graylog: https://github.com/Graylog2/graylog2-images/blob/master/docker/Dockerfile

How would I go about doing that? I'm not much into the arcane syslog format which needs custom parsing and has limits on size, so GELF seems to be the alternative. Or perhaps HTTP? In any case I can only find a decoder in the docs: https://hekad.readthedocs.org/en/latest/config/decoders/graylog_extended.html

What's the best way of connecting Heka to this?

**Comment by rafrombrc** [comment]
We use the issue tracker for specific, actionable bug reports and feature requests. General support requests are better directed to the mailing list (https://mail.mozilla.org/listinfo/heka). Thanks.

**Comment by haf** [comment]
Ok, thanks. However, isn't this a feature request?

**Comment by rafrombrc** [comment]
It's too vague to be a feature request. There are a number of different strategies that can be taken to get data from Heka into Greylog, and this issue is a request for information on how to approach that problem rather than an actionable issue that can be resolved by code. A feature request would provide a description of a specific encoder plugin that you were interested in seeing, for instance, preferably with some detail re: any particular config settings that might be desirable.

Also, I should warn you that the core Heka team isn't using Greylog, and we have lots and lots of priorities of our own improving the Heka core, and improving integration with tools that we do actually use, so this isn't likely to leap to the top of our priority queue any time soon. We'll happily provide support and guidance to any community members who want to tackle the problem, however.
