### ISSUE TITLE
Field.representation?

### ISSUE THREAD

**Issue by haf** [mozilla-services/heka#1588]
I was wondering what Field.representation means?

From https://github.com/mozilla-services/heka/blob/dev/message/message.proto#L32

Could we get some docs at https://hekad.readthedocs.org/en/dev/config/decoders/protobuf.html ?

**Comment by haf** [comment]
Would be good to get some input on the difference between a string in a field and a payload, too.

**Comment by haf** [comment]
And env_version and why it's being set to `0.2`, `0.8` and `1` in the sources.

**Comment by acesaro** [comment]
It's documented here: https://hekad.readthedocs.org/en/latest/message/index.html

**Comment by haf** [comment]
So if I read the docs correctly:

 - payload: the cherry on top of the pie, the reason for logging to exist – the LogLine message!
 - field.string_value: I have a dictionary of 'context' to send along, one key-value is string, I put that here.

Right?

And about representation: so this is the unit – some APIs, like NewRelic use this unit for scaling and transforming/normalising the data – is that the same for Heka? Can Heka unify two different values, e.g. KiB/s and B/s into B/s? Should it be `KiB s`<sup>`-1`</sup> or `KiB/s`? Can Heka understand counters/events versus rates versus rollups/aggregates/reservoir samples?

**Comment by rafrombrc** [comment]
Ultimately, you can use the message fields however you like. Heka's core message schema is loosely based on a syslog-ish data format (see https://tools.ietf.org/html/rfc5424#section-6) where payload maps to "MSG", or "a free-form message that provides information about the event."

When dealing with logging data, usually the raw contents of the log data (be it semi-structured text, JSON, whatever) will be in the payload field, while any structured data extracted from that that payload would be stored in separate message fields. This is a de facto, rather than de jure standard, however, you're free to use the available data fields however you see fit.

As for representation, no, Heka doesn't do any automatic conversion of values based on the representation of a field; representation just treated as an opaque piece of string metadata for the field. It is entirely possible, though, for Heka users to write filters that make use of the representation value to do such conversions manually.

**Comment by haf** [comment]
When it comes to semantic logging without losing the structure of the data; these are good reads:

 - https://github.com/influxdb/influxdb/issues/2102
 - http://metrics20.org/spec/
