### ISSUE TITLE
 getFileFromId cause TcpOutput stopped

### ISSUE THREAD

**Issue by tianlin** [mozilla-services/heka#1639]
filename := getQueueFilename(br.queue, id)
	if fileExists(filename) {
		if file, err = os.Open(filename); err == nil {
			foundId = id
		}
		return file, foundId, err
	}

	// If we got this far there's no file matching our id, try to find the
	// next one above.
	ids := sortedBufferIds(br.queue)
	if len(ids) == 0 || ids[len(ids)-1] < id {
		// No log file for us, not an error.
		return nil, 0, nil
	}
When getQueueFilename， next log does not exists。But it was created before sortedBufferIds，in this enviroment,  heka exited and print :
Streamoutput stopped: can't lookup subsequent file: open /opt/rizhiyi/heka/output_queue/TcpOuput/0.log: No such file or directory

I think, ids[len(ids)-1] < id should change to ids[len(ids)-1] <= id

**Comment by wolkykim** [comment]
We're also getting a similar error. From the caller function, ' NextRecord()', it seems getFileFromId() returns non-nil where there's no more next files to process. It tries to open "0.log". This happens occasionally. And I'm looking for the root cause of this.

                        nextReadFile, nextFileId, err := br.getFileFromId(br.readId + 1)
                        if err != nil {
                                return fmt.Errorf("can't lookup subsequent file: %s", err)

Any updates on this plz?

**Comment by rafrombrc** [comment]
Okay, I think @tianlin had the correct diagnosis, although the [change](https://github.com/mozilla-services/heka/compare/versions/0.10...buffer_reader_race_fix?expand=1) I made was slightly different. Anyway, I've pushed what I think will fix this issue to a branch called [buffer_reader_race_fix](https://github.com/mozilla-services/heka/tree/buffer_reader_race_fix). Is it possible for either of you to build from that branch and test to see if the problem is resolved?

**Comment by wolkykim** [comment]
Thanks. I'll try it and let you know the result.

**Comment by tianlin** [comment]
Thanks,the fix is ok.

**Comment by wolkykim** [comment]
No this fix doesn't work. It worked for a while but it crashed again with same error looking for 0.log file.

**Comment by rafrombrc** [comment]
@wolkykim Hrm. I'm pretty sure that the change I made (which is now merged into the versions/0.10 branch) resolves the issue that @tianlin reported. The fact that @tianlin is reporting that the issue is resolved implies that either a mistake was made somewhere and you're not actually running the new code that I wrote, or that you're seeing an error that looks similar but actually has a different cause.

If you're absolutely positive that you're running the latest code from the versions/0.10 branch and are still seeing the error, we're going to need to dig in more deeply. If this is so, I'd love for you to open another issue with details about what your configuration looks like, when the error happens, and anything else that you think might be relevant or helpful to the debugging process.

Thanks!
