### ISSUE TITLE
thoughts around max_buffer_size. automatic buffer size?

### ISSUE THREAD

**Issue by Dieterbe** [mozilla-services/heka#1657]
https://hekad.readthedocs.org/en/v0.10.0b0/buffering.html#buffering
* it's not documented what happens with `max_buffer_size = 0` (no limit) and the disk runs full (write errors). I saw that `(bf *BufferFeeder) QueueRecord()` returns an error but not sure what that means in the grand scheme of things wrt the message, ack's etc.

* it seems like if you want to play safe (leave headroom for other software writing stuff to disk in the future) you should set `max_buffer_size` to something significantly lower than how much free space you have, possibly wasting free space that you could have used for heka's buffer and heka prematurely treating the queue as full.
so it would be nice if heka:
  * could just check how much space is available on a hard drive and only write to the disk buffer if sufficient space is available.  This is racey, but in practice it should be fine, up to the user to say how much headroom to leave. it's basically the equivalent of contiously, automatically setting max_buffer_size based on how much space is available minus the headroom.
  * Alternatively perhaps heka could attempt a write and consider the queue full if it gets disk full errors. if feasible, this means maximum utilization.

**Comment by rafrombrc** [comment]
Re: the first issue, if your disk is full all bets are pretty much off, the behaviour at that point is undefined.

Re: the second, while it sounds nice to try to do some automatic disk space checking and etc., we have no intention of tackling that problem. There are so many edge cases across various platforms, file systems, etc., this feels like a major time sink for an almost guaranteed imperfect solution. I'd much rather leave things as they are now, where the job of managing queue sizes vs drive space is left explicitly to the user.

I'm possibly willing to consider special-casing disk full errors, so that Heka triggers the queue full behaviour when that happens, but that's not really very high on our priority queue, so it would probably have to come from an outside contributor.
