### ISSUE TITLE
Add Millisecond or better resolution capability to Timestamp format for ElasticSearch

### ISSUE THREAD

**Issue by kevpie** [mozilla-services/heka#1691]
I am in the middle of replacing Logstash with Heka in an ELK stack and rely on natural ordering all the way down to the millisecond or better.

Truncating Timestamp to seconds is unfortunate.  

Currently this is minor since the full timestamp can be sent in an additional field.

**Comment by jverhoeven** [comment]
I have exactly the same issue and am mostly surprised by how so many log frameworks (also syslog, fluentd) neglect the millisecond range.
 %L, %3 and %6 seem all unusable due to the choice of this library: http://godoc.org/github.com/cactus/gostrftime

Can we move this forward by getting millisecond into the cactus implementation or does the Heka team support moving to another lib as suggested in the bottom post in https://github.com/mozilla-services/heka/issues/1508?

**Comment by rafrombrc** [comment]
I don't have any particular preference with regard to which strftime implementation we use. If the cactus team is willing to accept PRs to add better resolution then great, and if not then I'm open to switching to a different library that does. Unfortunately we don't have any cycles internally to tackle this right now, so the effort will have to be driven from outside if it's to happen soon.

**Comment by kevpie** [comment]
I will try to move forward with this.

**Comment by sanga** [comment]
Would be awesome to get this fixed. This is a definitely pain point for us

**Comment by simonpasquier** [comment]
I've sent a PR to the cactus project. Hope it will be accepted...

**Comment by aodj** [comment]
Is there any chance of getting in a release soon? This is a really handy feature to have for those of us forwarding to ElasticSearch.
