### ISSUE TITLE
when can support output elasticsearch to manage template like logstash ?

### ISSUE THREAD

**Issue by swan-go** [mozilla-services/heka#1694]
when can support output elasticsearch to manage template like logstash ?

index => "logstash-default-%{type}-%{+YYYY.MM.dd}"
manage_template => true
template => "/etc/logstash/es-templates/default.json"
template_name => "logstash-default"
 template_overwrite => true

**Comment by swan-go** [comment]
My default.josn as below:
{
  "template": "logstash-default*",
  "settings" : {
    "number_of_shards" : 2,
    "number_of_replicas" : 0,
    "index" : {
      "query" : { "default_field" : "message" },
      "store" : { "compress" : { "stored" : true, "tv": true } }
    }
  },
  "mappings": {
    "_default_": {
      "_all": { "enabled": false },
      "_source": { "compress": true },
      "dynamic_templates": [
        {
          "string_template" : {
            "match" : "*",
            "mapping": { "type": "string", "index": "not_analyzed" },
            "match_mapping_type" : "string"
          }
        }
      ],
      "properties" : {
        "@fields": { "type": "object", "dynamic": true, "path": "full" },
        "@timestamp" : { "type" : "date", "index" : "not_analyzed" },
        "type" : { "type" : "string", "index" : "not_analyzed" },
        "level" : { "type" : "string", "index" : "not_analyzed" },
        "host" : { "type" : "string", "index" : "not_analyzed" },
        "path" : { "type" : "string", "index" : "not_analyzed" },
        "message" : { "type" : "string", "index" : "analyzed" },
        "apath" : { "type" : "string", "index" : "not_analyzed" },
        "bpath" : { "type" : "string", "index" : "analyzed" },
        "ua" : {
          "properties" : {
            "name" : { "type" : "string", "index" : "not_analyzed" },
            "os" : { "type" : "string", "index" : "not_analyzed" },
            "os_name" : { "type" : "string", "index" : "not_analyzed" },
            "device" : { "type" : "string", "index" : "not_analyzed" }
          }
        },
        "pos" : {
          "properties" : {
            "pkg" : { "type" : "string", "index" : "not_analyzed" },
            "file" : { "type" : "string", "index" : "not_analyzed" },
            "func" : { "type" : "string", "index" : "not_analyzed" },
            "line" : { "type" : "long", "index" : "not_analyzed" }
          }
        }
      }
    }
  }
}

**Comment by acesaro** [comment]
I personally just handle this in the deployment of the Elasticsearch instances themselves.  This, IMO, is where this really should be done, rather than the component sending data to Elasticsearch.  The json file can actually be deployed in the <elasticsearch install path/config/templates directory, as described in the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#config

**Comment by swan-go** [comment]
Sorry, I like get through heka to create es-template

**Comment by rafrombrc** [comment]
Sorry, but since Logstash is maintained by the ElasticSearch company, they have much more interest in very tightly coupling the two. Heka supports ElasticSearch, but is less tightly coupled and, as such, we're unlikely to support alternate means of setting up ES templates when there are other viable ways to accomplish the task such as that described by @acesaro.

**Comment by swan-go** [comment]
oh, I see, thanks
