### ISSUE TITLE
/mozilla-services/heka/message/message_matcher.go:21: undefined: tree

### ISSUE THREAD

**Issue by TuziBen** [mozilla-services/heka#1799]
Hi
I wanted to test some go file. But I got this error:

```
# github.com/mozilla-services/heka/message
../../../mozilla-services/heka/message/message_matcher.go:21: undefined: tree
FAIL	github.com/heka/plugins/file [build failed]
```
However I did not found any information about tree.

**Comment by rafrombrc** [comment]
Not sure how you're running the tests, or if that's even what you're doing, but in order to do anything you first need to set up your GOPATH correctly. The easiest way to do that is to source the `env.sh` file at the repo root: `source env.sh` or `. env.sh`, depending on your shell. After you do that, you can run tests by invoking the correct package path, e.g. `go test -v github.com/mozilla-services/heka/pipeline` or `go test -v github.com/mozilla-services/heka/plugins/tcp`.

**Comment by TuziBen** [comment]
Thanks  a lot.
I got it done. It is great to use heka.
