### ISSUE TITLE
Add lua plugin to distribution (the final package .deb of .rpm etc). Is it possible? How.

### ISSUE THREAD

**Issue by logrusorgru** [mozilla-services/heka#1800]
Hello. I use my own Go-plugins in the Heka. Some of them require their own Lua-plugins.I want to include all of them in the resulting package. How?

**Comment by logrusorgru** [comment]
I do not need to integrate them. All I need is the only one package.

**Comment by rafrombrc** [comment]
First, there's not enough information here for me to be able to answer your question; I'm honestly not sure what it is you're trying to accomplish. Second, we use the issue tracker for bug reports and feature requests. For support we ask that you use either the [mailing list](https://mail.mozilla.org/listinfo/heka) or the #heka IRC channel on irc.mozilla.org. Best results in the IRC channel will typically come from asking during normal California working hours, otherwise the mailing list is probably a better choice.

**Comment by logrusorgru** [comment]
Currently my `plugin_name.lua` is the independent file. I want put it into `.deb`-package. I build heak manually. There is a way to add (embed) Go-plugin to the .deb-pakage. What about lua plugins? Does it not a feature request?

**Comment by rafrombrc** [comment]
It's not a feature request unless you know that the feature doesn't already exist. The only way to find that out is to ask whether or not it's possible and, if it is, how to do it.

In this case it is possible, you just have to put the lua plugins you want to include into the source tree (e.g. decoders in the `sandbox/lua/decoders` folder, filters in the `sandbox/lua/filters` folder) before you run `cpack` or `make package` to build your packages.

**Comment by logrusorgru** [comment]
Thanks a lot.

You should to add a CONTRIBUTING file (or CONTRIBUTING.md) as described [here](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). And put your previous message into it.
