### ISSUE TITLE
when the disk is full, tcp output will send log Twice

### ISSUE THREAD

**Issue by czt1210** [mozilla-services/heka#1820]
when the disk is full, tcp output will send log Twice

**Comment by rafrombrc** [comment]
"Exactly once" delivery semantics is for all intents and purposes [impossible](http://bravenewgeek.com/you-cannot-have-exactly-once-delivery/). Heka doesn't yet achieve its goal ([hindsight](https://github.com/trink/hindsight) does a better job here), but in all cases Heka will choose an "at least once" strategy over one of "at most once".

In other words, yes, in pathological situations you might see the same message(s) delivered multiple times. That's by design, because the assumption is that it's better to get everything with possible duplicates than to miss events with no way to tell that anything has been lost. If duplication isn't acceptable in your use case, the recommended approach is to make sure you pass along each event's UUID and use this to perform de-duplication at the destination.
