### ISSUE TITLE
Unable to install heka

### ISSUE THREAD

**Issue by pruthig** [mozilla-services/heka#849]
Getting err while installing heka

pruthi@pruthi-linux:~/heka$ source build.sh 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find Go (missing: GO_VERSION GO_PLATFORM GO_ARCH) (Required is at
  least version "1.2")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGo.cmake:32 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
make: **\* No targets specified and no makefile found.  Stop.

Following are the env variables:

pruthi@pruthi-linux:~/heka/build$ env | grep GO
GO_PLATFORM=linux
GOBIN=/home/pruthi/heka/build/heka/bin
GOARCH=i386
GOROOT=/usr/local/go
GOOS=linux
GO_ARCH=i386
GOPATH=/home/pruthi/heka/build/heka
GOPLATFORM=linux
GO_VERSION=1.2

**Comment by jacktasia** [comment]
FWIW, I had this exact same issue on Ubuntu 14.04 once go 1.3 became a requirement (after successfully compiling back when it was 1.2). After upgrading my go to 1.4 and being able to successfully run `go version` `go env` and running/compiling go programs I was still getting 

    Could NOT find Go (missing: GO_VERSION GO_PLATFORM GO_ARCH) 

when running `source build.sh`

Finally I tried `rm -rf build/` and then `source build.sh` and it worked. This seems obvious in hindsight but took way too long to click for me because of the non-traditional way heka is built. Hopefully this will save someone else the time.
